blank_issues_enabled: true

contact_links:
  - name: Documentation
    url: https://github.com/bukasin1/zen/tree/main/docs
    about: Check the documentation before opening an issue.

  - name: Examples
    url: https://github.com/bukasin1/zen/tree/main/examples
    about: Explore the official examples.
